# Inner Products and Norms of Vectors

  ## Importing NumPy
    As usual, we will need to import NumPy


In [1]:
import numpy as np

  ## Introduction
  The most important vectors we will encounter will be $2$-dimensional complex vector which are of length $1$. In this section we will define the **inner product** of two vectors, and the **norm** (length) of a vector which is derived from the inner product of the vector with itself. The vectors of length $1$ are sometimes referred to as **unit vectors**. We will discuss complex unit vectors in $2$-dimensional space $\mathbb{C}^2$ and how they relate to qubits. This will lead to a discussion of the **Bloch sphere** which will be a useful way of understanding qubits and how quantum gates act on them.
    
  ### Inner Products
    
  **Inner Products** are a more general case of the **dot-product**, but for most of our purposes, they can be thought of as the same thing. The most basic case of an inner product and the one we will use the most often can be thought of as the product of a row vector and a column vector of the same dimension:

  \begin{align} ⟨A| = \begin{pmatrix}
  a_1, a_2, ⋯, a_n
  \end{pmatrix}, \quad \quad
  |B⟩ = \begin{pmatrix}
  b_1 \\ b_2 \\ \vdots \\ b_n
  \end{pmatrix} \end{align}

  Taking the inner product of ⟨A| and |B⟩ gives the following:

\begin{align} ⟨A|B⟩ &=
\begin{pmatrix}
a_1,& a_2,& ⋯, &a_n
\end{pmatrix}
\begin{pmatrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{pmatrix}
&=
a_1b_1 + a_2b_2 + ⋯ + a_nb_n
&= ∑ a_ib_i
\end{align}
   
  As a basic example, take the inner product of the following $2$-dimensional vectors,
\begin{align} ⟨A| = \begin{pmatrix}
3i, & 2
\end{pmatrix}, |B⟩= \begin{pmatrix}
5+2i \\ 1-i
\end{pmatrix} \end{align}

  as follows:

\begin{align}⟨A|B⟩ = \begin{pmatrix}
3i, & 2
\end{pmatrix}
\begin{pmatrix}
5+2i \\ 1-i
\end{pmatrix} &=
3i(5+2i) + 2(1-i)\\
&= 15i-6+2-2i\\
&= -4+13i
\end{align}
    
  In order to define a complex vector so that we can take its conjugate transpose, also called the **Hermitian conjugate**, we must define it as a **matrix**. So, suppose we have the following column vector (ket-vector):


\begin{align}
|A⟩ = \begin{pmatrix} 1-i \\ 3 \\ 2i \\ 5+i \end{pmatrix}
\end{align}
    
  
  Then of course its **Hermitian conjugate** would be the bra-vector\n",
    
\begin{align}
⟨A| = \begin{pmatrix}1+i, 3, -2i, 5-i \end{pmatrix}
\end{align}
    
    
  Now, in Python, we must remember to use "$j$" instead of "$i$" for the imaginary unit and we must define the $4 × 1$-matrix:"


In [4]:
    # Define the 4x1 matrix version of a column vector (instead of using the np.array() version):
A = np.matrix([[1-1j],
                [3],
                [2j],
                [5+1j]])

# Compute the Hermitian Conjugate:
A.H

matrix([[1.+1.j, 3.-0.j, 0.-2.j, 5.-1.j]])

 Now, to compute the inner product $⟨A|A⟩$ we can simple multiply the two matrix versions just computed:

In [5]:
np.dot(A.H, A)

matrix([[41.+0.j]])

  Let's define another $4$-dimensional complex row vector $⟨B|$:
    
\begin{align}
⟨B| = \begin{pmatrix}
-3i, 2+2i, -6i, -7
\end{pmatrix}
\end{align}
    
  
  Once we have defined this bra-vector, We can compute the following inner products:

\begin{align}
⟨B|A⟩,  ⟨B|B⟩, ⟨A|B ⟩.
\end{align}

Task 1: write the code in Python to calculate the above inner products.


In [8]:
# Define B as a 1x4 matrix
B = np.matrix([-3j, 2+2j, -6j, -7])
#Compute the Hermitian Conjugate of B, which is a ket-vector
B.H

matrix([[-0.+3.j],
        [ 2.-2.j],
        [-0.+6.j],
        [-7.-0.j]])

In [9]:
# Compute <B|A>
### TO DO ###
np.dot(B, A)

matrix([[-20.-4.j]])

In [10]:
# Compute <B|B>
### TO DO ###
print(np.dot(B, B.H))

[[102.+0.j]]


In [11]:
# Compute <A|B>
### TO DO ###
print(np.dot(A.H, B.H))


[[-20.+4.j]]



  There is a different kind of product on two vectors which we will cover later called the **[outer product](https://en.wikipedia.org/wiki/Outer_product)**. The outer product is a specific case of the tensor product and is written in this case by $ |A⟩⟨A|$. It is important to make this distinction now and note that the two **are not the same**. The **inner product** always yields a number, which can be complex valued if the two vectors are complex valued. The **outer product** in general gives a **matrix**.



In [9]:
np.dot(A, A.H)

matrix([[ 2. +0.j,  3. -3.j, -2. -2.j,  4. -6.j],
        [ 3. +3.j,  9. +0.j,  0. -6.j, 15. -3.j],
        [-2. +2.j,  0. +6.j,  4. +0.j,  2.+10.j],
        [ 4. +6.j, 15. +3.j,  2.-10.j, 26. +0.j]])


  For the more adventurous readers who understand how to multiply matrices, and to prepare for future computations where matrices are involved, we will compute a more general \"inner product\". If this does not make any sense to you and matrix multiplication is a foreign concept, we will discuss matrix multiplication in this chapter as a refresher, but now might be a good time to refresh your memory on how to multiply matrices if it is unfamiliar. When we discuss \\emph{measurements} and \\emph{expectation values} we will need to consider the case when there is a matrix in between the bra- and ket-vector. Take for example the Pauli-Z matrix, which we will discuss more later on:

\begin{align} Z = \begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix} \end{align}
    
  Now take the following bra-vector and ket-vector\n",

\begin{align} ⟨A|= \begin{pmatrix}
i/\sqrt{2}, & -i/\sqrt{2}
\end{pmatrix},    |A⟩ = \begin{pmatrix}
-i/\sqrt{2} \\ i/\sqrt{2}
\end{pmatrix} \end{align}

  Now, we can compute the following variation on the inner product\n",

\begin{align}
⟨A|Z|A⟩=\begin{pmatrix}
i/\sqrt{2}, & -i/\sqrt{2}
\end{pmatrix}
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
\begin{pmatrix}
-i/\sqrt{2} \\ i/\sqrt{2}
\end{pmatrix} \\
= \begin{pmatrix}
i/\sqrt{2}, & -i/\sqrt{2}
\end{pmatrix}
\begin{pmatrix}
-i/\sqrt{2} \\ -i/\sqrt{2}
\end{pmatrix} \\
= 1/2 - 1/2 \\
= 0
\end{align}

    
  We will encounter such calculations many more times when we discuss measurements and expectations. If this is a little confusing, it is not important to worry too much about it just yet. We will cover matrix multiplication shortly, and later we will discuss measurements and expectation values, at which point we should be comfortable computing more general version of this strange \"inner product\".

   ## Exercises
  
  1. Compute the  following inner product by hand:
        
\begin{align}\begin{pmatrix}2, & 3i\end{pmatrix}\begin{pmatrix}1+i \\ 4\end{pmatrix}\end{align}
        
  2. Write Python code to compute the previous inner product.
  3. Compute the following inner product by hand:
\begin{align}
\begin{pmatrix}3i, & 1+2i, & 4, & 2i\end{pmatrix}
\begin{pmatrix}5 \\ 1-2i \\ -3 \\ -i/2\end{pmatrix}
\end{align}

  4. Write Python code to compute the previous inner product.
  5. For the more adventurous who understand how to multiply matrices, and to prepare for future computations where matrices are involved, compute the following more general \"inner product\":

\begin{align}
\begin{pmatrix}1/\sqrt{2}, & -1/\sqrt{2} \end{pmatrix}
\begin{pmatrix} 1&0\\\\0&-1 \end{pmatrix}
\begin{pmatrix}1/\sqrt{2} \\ -1/\sqrt{2} \end{pmatrix}
\end{align}


2 * (1 + i) + 3i * (4) = 2 + 2i + 12i = 2 + 14i

In [13]:
# 2

A_2 = np.array([2-0j, 0+3j])
B_2 = np.array([[1+1j],
                [4]])

print(np.dot(A_2, B_2))


[2.+14.j]


3i * 5 + (1 + 2i) * (1 - 2i) + 4 * (-3) + 2i * (-i/2) = 15i + 1 -2i + 2i +4 -12 + 1 = 1 + 15i - 8 + 1 = -6 + 15i

In [16]:
# 4
import math


A_4 = np.array([0+3j, 1+2j, 4, 0+2j])
B_4 = np.array([[5],
                [1-2j],
                [-3+0j],
                [0-0.5j],])

print(np.dot(A_4, B_4))



[-6.+15.j]


In [17]:
# 5
sqrt2 = math.sqrt(2)
A_5 = np.array([1/sqrt2, -1*(1/sqrt2)])
B_5 = np.array([[1, 0],
                [0, -1]])

C_5 = np.array([[1/sqrt2],
                [-1*(1/sqrt2)]])

print(np.dot(np.dot(A_5, B_5), C_5))

[0.]
