<font style="font-size:28px;" align="left"><b>Tensor Product</b></font>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $
$ \newcommand{\greenbit}[1] {\mathbf{{\color{green}#1}}} $
$ \newcommand{\bluebit}[1] {\mathbf{{\color{blue}#1}}} $
$ \newcommand{\redbit}[1] {\mathbf{{\color{red}#1}}} $
$ \newcommand{\brownbit}[1] {\mathbf{{\color{brown}#1}}} $
$ \newcommand{\blackbit}[1] {\mathbf{{\color{black}#1}}} $


# Tensor Products of Vectors

## Importing NumPy

We will need to import NumPy for tensor products.

In [1]:
!pip3 install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.



$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $
$ \newcommand{\greenbit}[1] {\mathbf{{\color{green}#1}}} $
$ \newcommand{\bluebit}[1] {\mathbf{{\color{blue}#1}}} $
$ \newcommand{\redbit}[1] {\mathbf{{\color{red}#1}}} $
$ \newcommand{\brownbit}[1] {\mathbf{{\color{brown}#1}}} $
$ \newcommand{\blackbit}[1] {\mathbf{{\color{black}#1}}} $

Tensor product is defined between any two matrices. The result is a new probably bigger matrix.

Before giving its formal definition, we define it based on examples.

We start with a simple case.

<i>A vector is also a matrix. Therefore, tensor product can be defined between two vectors or between one vector and one matrix.</i>

<h3> Tensor product of two vectors </h3>

We have two vectors: $ u = \myrvector{-2\\3} $ and $ v = \myrvector{1 \\ 2 \\ -3} $.

The tensor product of $u$ and $ v $ is denoted by $ u \otimes v $.

We may consider the tensor product as extending $ u $ by $ v $:

One of the most common tensor products we will encounter throughout the following chapters of the book will be the tensor product of two qubits, which are represented by $2$-dimensional vector which have length (or "norm") $1$.

The general rule for the tensor product of two $2$-dimensional vectors is as follows:

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} =
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_2 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}
\end{pmatrix} =
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_2b_1 \\ a_2b_2
\end{pmatrix}
\end{align}


Here is a numerical example:

\begin{align}
\begin{pmatrix}
2 \\ 5
\end{pmatrix} \otimes
\begin{pmatrix}
3 \\ 1
\end{pmatrix} =
\begin{pmatrix}
2 \begin{pmatrix}
3 \\ 1
\end{pmatrix} \\ 5 \begin{pmatrix}
3 \\ 1
\end{pmatrix}
\end{pmatrix} =
\begin{pmatrix}
2 \cdot 3 \\ 2 \cdot 1 \\ 5 \cdot 3 \\ 5 \cdot 1
\end{pmatrix} =
\begin{pmatrix}
6 \\ 2 \\ 15 \\ 5
\end{pmatrix}
\end{align}


As another example consider the following Tensor product:

$$
    u \otimes v =  \myrvector{-2\\3} \otimes \myrvector{1 \\ 2 \\ -3} =
   \myrvector{ -2 \cdot  \myrvector{1 \\ 2 \\ -3} \\ 3 \cdot  \myrvector{1 \\ 2 \\ -3} } =
   \myrvector{ -2 \\ -4 \\ 6 \\ 3 \\ 6 \\ -9 }.
$$

Here, $ -2 $ in $ u $ is replaced with the vector $ (-2  v) $, and $ 3 $ in $ u $ is replaced with the vector $ 3 v $.

Thus each entry of $ u $ is replaced by a 3-dimensional vector, and the dimension of the result vector is $ 6~(=2 \cdot 3) $.

Algorithmically, each element in $ u $ is replaced by the multiplication of this element with the vector $ v $.

Let's find $ v \otimes u $ in Python.

In [2]:
# vector v
v = [1,2,-3]
# vector u
u=[-2,3]

vu = []

for i in range(len(v)): # each element of v will be replaced
    for j in range(len(u)): # the vector u will come here after multiplying with the entry there
        vu.append( v[i] * u[j] )

print("v=",v)
print("u=",u)
print("vu=",vu)

v= [1, 2, -3]
u= [-2, 3]
vu= [-2, 3, -4, 6, 6, -9]


For an example using Python we will use the "np.kron()" function, which is the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product),

> "In mathematics, the Kronecker product, sometimes denoted by ⊗, is an operation on two matrices of arbitrary size resulting in a block matrix. It is a generalization of the outer product (which is denoted by the same symbol) from vectors to matrices, and gives the matrix of the tensor product with respect to a standard choice of basis. The Kronecker product should not be confused with the usual matrix multiplication, which is an entirely different operation."

In [3]:
# Define two ket-vectors

A = np.array([[2],
              [5]])

B = np.array([[3],
              [1]])

# Take the Kronecker (tensor) product of the two column vectors
np.kron(A,B)

array([[ 6],
       [ 2],
       [15],
       [ 5]])

We can also define these two vectors as matrices which will allow us to compute Hermitian conjugates. The Kronecker product function 'np.kron()' will work all the same:

In [4]:
# Define the ket-vectors as 2x1 column matrices:
ket_A = np.matrix([[2],
                   [5]])

ket_B = np.matrix([[3],
                   [1]])

# Compute their Kronecker product
np.kron(ket_A, ket_B)

matrix([[ 6],
        [ 2],
        [15],
        [ 5]])

This can also be done with complex vectors:

In [5]:
# Define the ket-vectors as 2x1 column matrices:
ket_psi = np.matrix([[2-1j],
                     [3j]])

ket_phi = np.matrix([[-3],
                     [4-2j]])

# Compute their Kronecker product
np.kron(ket_psi, ket_phi)

matrix([[-6. +3.j],
        [ 6. -8.j],
        [-0. -9.j],
        [ 6.+12.j]])

Here is a more complicated example with two vectors of different dimensions:

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix} =
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix} \\
a_2 \begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix}
\end{pmatrix} =
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_1b_3 \\ a_2b_1 \\ a_2b_2 \\ a_2b_3
\end{pmatrix}
\end{align}

Here is a corresponding numerical example:

\begin{align}
\begin{pmatrix}
1 \\ 4
\end{pmatrix} \otimes
\begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix} =
\begin{pmatrix}
1 \begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix} \\
4 \begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix}
\end{pmatrix} =
\begin{pmatrix}
5 \\ 2 \\ 4 \\ 20 \\ 8 \\ 16
\end{pmatrix}
\end{align}

Here is the code for computing this tensor product:

In [6]:
ket_X = np.matrix([[1],
                   [4]])

ket_Y = np.matrix([[5],
                   [2],
                   [4]])

np.kron(ket_X, ket_Y)

matrix([[ 5],
        [ 2],
        [ 4],
        [20],
        [ 8],
        [16]])

<h3> Task 1 </h3>

Find $ u \otimes v $ and $ v \otimes u $ for the given vectors $ u = \myrvector{-2 \\ -1 \\ 0 \\ 1} $ and $ v = \myrvector{ 1 \\ 2 \\ 3 } $.

In [7]:
ket_X = np.matrix([[-2],
                   [-1],
                   [0],
                   [1]])

ket_Y = np.matrix([[1],
                   [2],
                   [3]])

np.kron(ket_X, ket_Y)

matrix([[-2],
        [-4],
        [-6],
        [-1],
        [-2],
        [-3],
        [ 0],
        [ 0],
        [ 0],
        [ 1],
        [ 2],
        [ 3]])

<h3> Note:</h3>

Tensor products are useful when we have a system composed by two (or more) sub-systems.

Any new entry after tensoring represents a pair of entries, each of which comes from one of the sub-sytems.

We will see the usage of tensor products in the main tutorial.

<h3> Tensor product of two matrices </h3>

The definition is the same.

Let's find $ M \otimes N $ and $ N \otimes M $ for the given matrices
$
    M = \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2 \\ 1 & 2 & -2} ~~\mbox{and}~~
    N = \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0}.
$

$ M \otimes N $: Each element of $ M $ will be replaced with the whole matrix $ N $ after multiplying with this element.

$$
    M \otimes N =
    \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2 \\ 1 & 2 & -2} \otimes \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0}
    =
    \mymatrix{rrr}{ -1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 0 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} \\
    -2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & -1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} \\
    1 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & 2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0} & -2 \mymatrix{rrr}{0 & 2 & 1 \\ 3 & -1 & -2 \\ -1 & 1 & 0}}
$$

Calculating by hand looks a boring task because of many repetitions.

We do this once by hand (in mind), and then check the result by Python.

$$
    M \otimes N = \mymatrix{rrrrrrrrr}{
        0 & -2 & -1 & 0 & 0 & 0 & 0 & 2 & 1 \\
        -3 & 1 & 2 & 0 & 0 & 0 & 3 & -1 & -2 \\
        1 & -1 & 0 & 0 & 0 & 0 & -1 & 1 & 0 \\
        0 & -4 & -2 & 0 & -2 & -1 & 0 & 4 & 2 \\
        -6 & 2 & 4 & -3 & 1 & 2 & 6 & -2 & -4 \\
        2 & -2 & 0 & 1 & -1 & 0 & -2 & 2 & 0 \\
        0 & 2 & 1 & 0 & 4 & 2 & 0 &  -4 & -2 \\
        3 & -1 & -2 & 6 & -2 & -4 & -6 & 2 & 4 \\
        -1 & 1 & 0 & -2 & 2 & 0 & 2 & -2 & 0
    }
$$

Now, we find the same matrix in Python.

This time we use four nested for-loops.

In [8]:
# matrix M
M = [
    [-1,0,1],
    [-2,-1,2],
    [1,2,-2]
]

# matrix N
N = [
    [0,2,1],
    [3,-1,-2],
    [-1,1,0]
]

# MN will be a (9x9)-dimensional matrix
# prepare it as a zero matrix
# this helps us to easily fill it
MN=[]
for i in range(9):
    MN.append([])
    for j in range(9):
        MN[i].append(0)

for i in range(3): # row of M
    for j in range(3): # column of M
        for k in range(3): # row of N
            for l in range(3): # column of N
                MN[i*3+k][3*j+l] = M[i][j] * N[k][l]

print("M-tensor-N is")
for i in range(9):
    print(MN[i])

M-tensor-N is
[0, -2, -1, 0, 0, 0, 0, 2, 1]
[-3, 1, 2, 0, 0, 0, 3, -1, -2]
[1, -1, 0, 0, 0, 0, -1, 1, 0]
[0, -4, -2, 0, -2, -1, 0, 4, 2]
[-6, 2, 4, -3, 1, 2, 6, -2, -4]
[2, -2, 0, 1, -1, 0, -2, 2, 0]
[0, 2, 1, 0, 4, 2, 0, -4, -2]
[3, -1, -2, 6, -2, -4, -6, 2, 4]
[-1, 1, 0, -2, 2, 0, 2, -2, 0]


We find $ N \otimes M $ in Python.

We use the same code by interchanging $ N $ and $ M $.

In [11]:

# matrices M and N were defined above

# matrix NM will be prepared as a (9x9)-dimensional zero matrix
NM=[]
for i in range(9):
    NM.append([])
    for j in range(9):
        NM[i].append(0)

for i in range(3): # row of N
    for j in range(3): # column of N
        for k in range(3): # row of M
            for l in range(3): # column of M
                NM[i*3+k][3*j+l] = N[i][j] * M[k][l]

print("N-tensor-M is")
for i in range(9):
    print(NM[i])

N-tensor-M is
[0, 0, 0, -2, 0, 2, -1, 0, 1]
[0, 0, 0, -4, -2, 4, -2, -1, 2]
[0, 0, 0, 2, 4, -4, 1, 2, -2]
[-3, 0, 3, 1, 0, -1, 2, 0, -2]
[-6, -3, 6, 2, 1, -2, 4, 2, -4]
[3, 6, -6, -1, -2, 2, -2, -4, 4]
[1, 0, -1, -1, 0, 1, 0, 0, 0]
[2, 1, -2, -2, -1, 2, 0, 0, 0]
[-1, -2, 2, 1, 2, -2, 0, 0, 0]


<h3> Task 2 </h3>

Find $ A \otimes B $ for the given matrices
$
    A = \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2} ~~\mbox{and}~~
    B = \mymatrix{rr}{0 & 2 \\ 3 & -1 \\ -1 & 1 }.
$

In [30]:
# matrix M
A = [
    [-1,0,1],
    [-2,-1,2],
]

# matrix N
B = [
    [0,2],
    [3,-1],
    [-1,1]
]

AB = []
for i in range(6):
    AB.append([])
    for j in range(6):
        AB[i].append(0)

for i in range(2): # row of A
    for j in range(3): # column of A
        for k in range(3): # row of B
            for l in range(2): # column of B
                x = i*3+k
                y = 2*j+l
                AB[x][y] = A[i][j] * B[k][l]


print("A-tensor-B is")
for i in range(6):
    print(AB[i])

A-tensor-B is
[0, -2, 0, 0, 0, 2]
[-3, 1, 0, 0, 3, -1]
[1, -1, 0, 0, -1, 1]
[0, -4, 0, -2, 0, 4]
[-6, 2, -3, 1, 6, -2]
[2, -2, 1, -1, -2, 2]


<h3> Task 3 </h3>

Find $ B \otimes A $ for the given matrices
$
    A = \mymatrix{rrr}{-1 & 0 & 1 \\ -2 & -1 & 2} ~~\mbox{and}~~
    B = \mymatrix{rr}{0 & 2 \\ 3 & -1 \\ -1 & 1 }.
$

You can use the code in your (our) solution for Task 2.

But please be careful with the indices and range values, and how they are interchanged (!)

In [1]:
# matrix M
A = [
    [-1,0,1],
    [-2,-1,2],
]

# matrix N
B = [
    [0,2],
    [3,-1],
    [-1,1]
]

BA = []
for i in range(6):
    BA.append([])
    for j in range(6):
        BA[i].append(0)

for i in range(3): # row of B
    for j in range(2): # column of B
        for k in range(2): # row of A
            for l in range(3): # column of A
                x = i*2+k
                y = 3*j+l
                BA[x][y] = B[i][j] * A[k][l]


print("B-tensor-A is")
for i in range(6):
    print(BA[i])

B-tensor-A is
[0, 0, 0, -2, 0, 2]
[0, 0, 0, -4, -2, 4]
[-3, 0, 3, 1, 0, -1]
[-6, -3, 6, 2, 1, -2]
[1, 0, -1, -1, 0, 1]
[2, 1, -2, -2, -1, 2]


## Exercises

1. Using the following rule,
\begin{align}
\begin{pmatrix}
a_1 \\ a_2 \\ a_3
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} =
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_2\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_3\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}
\end{pmatrix} =
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_2b_1 \\ a_2b_2 \\ a_3b_1 \\ a_3b_2
\end{pmatrix}
\end{align}

compute the following tensor/Kroneckar product by hand:

\begin{align}
\begin{pmatrix}
2 \\ 7 \\ 3
\end{pmatrix} \otimes
\begin{pmatrix}
5 \\ 9
\end{pmatrix}
\end{align}

[
  2 * 5 <br>
  2 * 9 <br>
  7 * 5 <br>
  7 * 9 <br>
  3 * 5 <br>
  3 * 9 
] 

=

[
  10 <br>
  18 <br>
  35 <br>
  63 <br>
  15 <br>
  27 <br>
]

2. Write Python code to compute the above computation using the 'np.kron()' function. Remember to define two column (ket) vectors as matrices first.  

In [34]:
ket_X = np.matrix([[2],
                   [7],
                   [3]])

ket_Y = np.matrix([[5],
                   [9]])

np.kron(ket_X, ket_Y)

matrix([[10],
        [18],
        [35],
        [63],
        [15],
        [27]])

3. Derive a general rule for the following tensor product by performing the tensor product inside the parenthesis first:

\begin{align}
\left( \begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}\right) \otimes
\begin{pmatrix}
c_1 \\ c_2
\end{pmatrix}
\end{align}

[
  a1 * b1 <br>
  a1 * b2 <br>
  a2 * b1 <br>
  a2 * b2 <br>
] TENSOR C

= 

[
  a1 * b1 * c1 <br>
  a1 * b1 * c2 <br>
  a1 * b2 * c1 <br>
  a1 * b2 * c2 <br>
  a2 * b1 * c1 <br>
  a2 * b1 * c2 <br>
  a2 * b1 * c1 <br>
  a2 * b2 * c2 
]

4. Now derive a general rule for the following tensor product by performing the tensor product in the parenthesis first:

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes
\left( \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \otimes
\begin{pmatrix}
c_1 \\ c_2
\end{pmatrix}\right)
\end{align}

Convince yourself that your results from the previous two computations are in fact equal.

A TENSOR [
  b1 * c1 <br>
  b1 * c2 <br>
  b2 * c1 <br>
  b2 * c2
]

= 

[
  a1 * b1 * c1 <br>
  a1 * b1 * c2 <br>
  a1 * b2 * c1 <br>
  a1 * b2 * c2 <br>
  a2 * b1 * c1 <br>
  a2 * b1 * c2 <br>
  a2 * b1 * c1 <br>
  a2 * b2 * c2
]

5. Write Python code to compute $|0\rangle \otimes |0 \rangle $.
6. Write Python code to compute $|0\rangle \otimes |1 \rangle $.
7. Write Python code to compute $|1\rangle \otimes |0 \rangle $.
8. Write Python code to compute $|1\rangle \otimes |1 \rangle $.

In [36]:
ket_0 = np.matrix([[1],
                   [0]])

ket_1 = np.matrix([[0],
                   [1]])

result_5 = np.kron(ket_0, ket_0)
result_6 = np.kron(ket_0, ket_1)
result_7 = np.kron(ket_1, ket_0)
result_8 = np.kron(ket_1, ket_1)

print(f"Result 5 = {result_5}")
print(f"Result 6 = {result_6}")
print(f"Result 7 = {result_7}")
print(f"Result 8 = {result_8}")

Result 5 = [[1]
 [0]
 [0]
 [0]]
Result 6 = [[0]
 [1]
 [0]
 [0]]
Result 7 = [[0]
 [0]
 [1]
 [0]]
Result 8 = [[0]
 [0]
 [0]
 [1]]
