# Tensor Products of Matrices

## Imports

As usual, we will need NumPy. So, let's import it now. 

In [1]:
import numpy as np

In this section we will discuss how to take tensor products of matrices in order to later build quantum gates that operate on many qubits at once. Understanding the basics of tensor products of matrices is fundamental to understanding quantum logic gates and quantum circuits. For the tensor product of two $2 \times 2$ matrices, the general rule is as follows:

\begin{align}
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix} \otimes 
\begin{pmatrix}
x & y \\
z & w
\end{pmatrix} = 
\begin{pmatrix}
a \begin{pmatrix}
x & y \\
z & w
\end{pmatrix} & b \begin{pmatrix}
x & y \\
z & w
\end{pmatrix} \\
c \begin{pmatrix}
x & y \\
z & w
\end{pmatrix} & d \begin{pmatrix}
x & y \\
z & w
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
ax & ay & bx & by \\
az & aw & bz & bw \\
cx & cy & dx & dy \\
cz & cw & dz & dw
\end{pmatrix}
\end{align}

Here is a basic numerical example:

\begin{align}
\begin{pmatrix}
2 & 3 \\
6 & 1
\end{pmatrix} \otimes
\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix} = 
\begin{pmatrix}
2 \begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix}& 3\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix} \\
6\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix} & 1\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
14 & 20 & 21 & 30 \\
18 & 8 & 27 & 12 \\
42 & 60 & 7 & 10 \\
54 & 24 & 9 & 4
\end{pmatrix}
\end{align}

We can again use the 'np.kron()' function to perform this computation in Python, just as we did for qubit state vectors.

> Indented block



In [2]:
A = np.matrix([[2, 3],
               [6, 1]])

B = np.matrix([[7, 10],
               [9, 4]])

np.kron(A,B)

matrix([[14, 20, 21, 30],
        [18,  8, 27, 12],
        [42, 60,  7, 10],
        [54, 24,  9,  4]])

In quantum computing, if we have basis states such as

\begin{align}
|010\rangle &= |0\rangle \otimes |1\rangle \otimes |0\rangle \\
&= \begin{pmatrix}
1\\0
\end{pmatrix} \otimes 
\begin{pmatrix}
0\\1
\end{pmatrix} \otimes 
\begin{pmatrix}
1\\0
\end{pmatrix} \\
&= \begin{pmatrix}
0\\0\\1\\0\\0\\0\\0\\0
\end{pmatrix}
\end{align}

we can operate on them using tensor product of operators. In particular, to operate on a three qubit basis state such at this, we need the tensor product of three $2 \times 2$ matrix. For example, with the following four operators:

\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}

We can form tensor products of matrices (gates) such as $H \otimes X \otimes I$ and $Z \otimes Z \otimes H$, and any other three matrix combination you might dream up. Let's define a basis state $|01\rangle$ and compute a few operators that will operate on this basis state:

In [ ]:
#Define the basis state |01>
u = np.matrix([[1],
               [0]])

d = np.matrix([[0],
               [1]])

ud = np.kron(u,d)

print(ud)

[[0]
 [1]
 [0]
 [0]]


In [3]:
# Define the matrices X, Y, Z, and H
X = np.matrix([[0, 1],
               [1, 0]])

Y = np.matrix([[0, -1j],
               [1j, 0]])

Z = np.matrix([[1, 0],
               [0, -1]])

H = (1/np.sqrt(2))*np.matrix([[1, 1],
                              [1, -1]])

Now let's compute the following four tensor products:

\begin{align}
X \otimes Y, \quad X \otimes Z, \quad H \otimes H
\end{align}

In [4]:
print(np.kron(X, Y))

[[0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]


In [5]:
print(np.kron(X, Z))

[[ 0  0  1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]


In [6]:
print(np.kron(H, H))

[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


Now, we can compute the action of these matrices on $|01\rangle$ as:

\begin{align}
(X \otimes Y)(|01\rangle) = (X \otimes Y)(|0\rangle \otimes |1\rangle) = X|0\rangle \otimes Y|1\rangle 
\end{align}

\begin{align}
(X \otimes Z)(|01\rangle) = (X \otimes Z)(|0\rangle \otimes |1\rangle) = X|0\rangle \otimes Z|1\rangle 
\end{align}

\begin{align}
(H \otimes H)(|01\rangle) = (H \otimes H)(|0\rangle \otimes |1\rangle) = H|0\rangle \otimes H|1\rangle 
\end{align}

In [ ]:
XY = np.kron(X, Y)
XZ = np.kron(X, Z)
HH = np.kron(H, H)

In [ ]:
print(XY * ud)

[[0.+0.j]
 [0.+0.j]
 [0.-1.j]
 [0.+0.j]]


In [ ]:
print(XZ * ud)

[[ 0]
 [ 0]
 [ 0]
 [-1]]


In [ ]:
print(HH * ud)

[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]


## Exercises

1. Compute the following tensor product by hand:

\begin{align}
\begin{pmatrix}
11 & 2 \\
3 & 5
\end{pmatrix} \otimes
\begin{pmatrix}
7 & 8 \\ 
0 & 1
\end{pmatrix}
\end{align}

[
  11 * 7, 11 * 8, 2 * 7, 2 * 8, <br>
  11 * 0, 11 * 1, 2 * 0, 2 * 1, <br>
  3  * 7, 3  * 8, 5 * 7, 5 * 8, <br>
  3  * 0, 3  * 1, 5 * 0, 5 * 1  <br>
]

= 

[
  77, 88, 14, 16, <br>
  0 , 11 , 0, 2, <br>
  21, 24, 35, 40, <br>
  0, 3, 0, 5  <br>
]

#### Compute the following tensor products by hand:

2. $X \otimes X$
3. $Z \otimes Y$
4. $H \otimes X$


\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}

2.

[ <br>
  0 * 0, 0 * 1, 1 * 0, 1 * 1, <br>
  0 * 1, 0 * 0, 1 * 1, 1 * 0, <br>
  1 * 0, 1 * 1, 0 * 0, 0 * 1, <br>
  1 * 1, 1 * 0, 0 * 1, 0 * 0  <br>
]

= 
[ <br>
  0, 0, 0, 1, <br>
  0, 0, 1, 0, <br>
  0, 1, 0, 0, <br>
  1, 0, 0, 0, <br>
]


3. 
[<br>
  1 * 0, 1 * i, 0 * 0, 0 * i <br>
  1 * -i, 1 * 0, 0 * -i, 0 * 0, <br>
  0 * 0, 0 * i, -1 * 0, -1 * i  <br>
  0 * -i, 0 * 0, -1 * -i, -1 * 0 <br>
]

= 
[<br>
  0, i, 0, 0, <br>
  -i, 0, 0, 0, <br>
  0, 0, 0, -i, <br>
  0, 0, i, 0 <br>
]


4. 
1/√2 * [ <br>
  1 * 0, 1 * 1, 1 * 0, 1 * 1, <br>
  1 * 1, 1 * 0, 1 * 1, 1 * 0, <br>
  1 * 0, 1 * 1, -1 * 0, -1 * 1, <br>
  1 * 1, 1 * 0, -1 * 1, -1 * 0 <Br>
]

= 
1/√2 *  [ <br>
  0, 1, 0, 1, <br>
  1, 0, 1, 0, <br>
  0, 1, 0, -1, <br>
  1, 0, -1, 0 <br>
]

#### Write Python code to compute the tensor products:

5. $X \otimes X$
6. $Z \otimes Y$
7. $H \otimes X$
8. $H \otimes H$


\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}

In [9]:
X = np.matrix([[0, 1],
               [1, 0]])

Y = np.matrix([[0, -1j],
               [1j, 0]])

Z = np.matrix([[1, 0],
               [0, -1]])

H = (1/np.sqrt(2))*np.matrix([[1, 1],
                              [1, -1]])


XX = np.kron(X, X)
ZY = np.kron(Z, Y)
HX = np.kron(H, X)
HH = np.kron(H, H)

print(f"5. Result = {XX}")
print(f"6. Result = {ZY}")
print(f"7. Result = {HX}")
print(f"8. Result = {HH}")


5. Result = [[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
6. Result = [[ 0.+0.j  0.-1.j  0.+0.j  0.-0.j]
 [ 0.+1.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.-0.j -0.+0.j  0.+1.j]
 [ 0.+0.j  0.+0.j -0.-1.j -0.+0.j]]
7. Result = [[ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678 -0.         -0.70710678]
 [ 0.70710678  0.         -0.70710678 -0.        ]]
8. Result = [[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


9. Write Python code to verify that $(H \otimes H) \otimes H = H \otimes (H \otimes H)$. 

In [12]:
left = np.kron(np.kron(H, H), H)
right = np.kron(H, np.kron(H, H))


for (i, row) in enumerate(left):
  for (j, column) in enumerate(row):
    print(left[i][j] == right[i][j])

[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]
[[ True  True  True  True  True  True  True  True]]


each cell has the same value, therefore operations are equal

#### Use the following code defining the basis state $|010 \rangle $ and the relevant tensor products to compute the following: 

10. $(X \otimes X \otimes Y)|010 \rangle$
11. $(X \otimes Z \otimes H)|010 \rangle$
12. $(H \otimes H \otimes H)|010 \rangle$

In [14]:
# Define the matrices X, Y, Z, and H:
X = np.matrix([[0, 1],
               [1, 0]])

Y = np.matrix([[0, -1j],
               [1j, 0]])

Z = np.matrix([[1, 0],
               [0, -1]])

H = (1/np.sqrt(2))*np.matrix([[1, 1],
                              [1, -1]])

# Define the following tensor products:
XY = np.kron(X, Y)
XZ = np.kron(X, Z)
HH = np.kron(H, H)

# Define the following additional tensor products:
XXY = np.kron(X, XY)
XZH = np.kron(XZ, H)
HHH = np.kron(HH, H)

# spin-up and spin-down
u = np.matrix([[1],
               [0]])

d = np.matrix([[0],
               [1]])

# Define the basis state |01
ud = np.kron(u,d)

# Define the basis state |010>:
udu = np.kron(ud, u)

In [16]:
print(f"10 = {XXY * udu}")
print(f"11 = {XZH * udu}")
print(f"12 = {HHH * udu}")

10 = [[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+1.j]
 [0.+0.j]
 [0.+0.j]]
11 = [[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]
 [-0.70710678]]
12 = [[ 0.35355339]
 [ 0.35355339]
 [-0.35355339]
 [-0.35355339]
 [ 0.35355339]
 [ 0.35355339]
 [-0.35355339]
 [-0.35355339]]
